### ISSUE TITLE
Problem installing hygese via pip

### ISSUE THREAD

**Issue by FrancoG85** [chkwon/PyHygese#19]
Hello, I have been facing some troubles while installing hygese via pip.

I followed the instruction, but when I tried to install hygese an error come up. The error says " cmake isn´t an internal or external command". I´ve installed and added to the path cmake.. So I don´t understand why this is happening.

I am currently using spider on windows 10.

**Comment by chkwon** [comment]
Have you tried running `cmake` in Spyder? 

Or, have you tried installing `hygese` in the Windows Powershell?

**Comment by FGE85** [comment]
Hi chkwon I thank you for your answer. Recently I was using successfully the julia wrapper, but now I have to use python and I still cant install hygese.

The package gcc is still available?  I cant find it and when I try to install hygese without it I get:
 × Building wheel for hygese (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [225 lines of output]
      running bdist_wheel
      running build
      running build_py
      x HGS-CVRP-2.0.0/
      x HGS-CVRP-2.0.0/.github/
      x HGS-CVRP-2.0.0/.github/workflows/
      x HGS-CVRP-2.0.0/.github/workflows/CI_Build.yml
      x HGS-CVRP-2.0.0/.gitignore
      x HGS-CVRP-2.0.0/CMakeLists.txt
      x HGS-CVRP-2.0.0/Instances/
      x HGS-CVRP-2.0.0/Instances/CVRP/
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT1.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT10.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT11.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT12.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT14.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT2.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT3.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT4.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT5.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT6.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT7.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT8.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/CMT9.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_1.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_10.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_11.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_12.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_14.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_15.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_16.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_17.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_18.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_19.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_2.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_20.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_3.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_4.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_5.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_6.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_7.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_8.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/Golden_9.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n1001-k43.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n101-k25.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n106-k14.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n110-k13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n115-k10.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n120-k6.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n125-k30.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n129-k18.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n134-k13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n139-k10.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n143-k7.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n148-k46.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n153-k22.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n157-k13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n162-k11.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n167-k10.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n172-k51.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n176-k26.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n181-k23.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n186-k15.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n190-k8.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n195-k51.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n200-k36.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n204-k19.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n209-k16.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n214-k11.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n219-k73.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n223-k34.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n228-k23.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n233-k16.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n237-k14.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n242-k48.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n247-k50.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n251-k28.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n256-k16.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n261-k13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n266-k58.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n270-k35.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n275-k28.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n280-k17.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n284-k15.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n289-k60.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n294-k50.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n298-k31.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n303-k21.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n308-k13.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n313-k71.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n317-k53.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n322-k28.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n327-k20.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n331-k15.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n336-k84.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n344-k43.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n351-k40.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n359-k29.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n367-k17.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n376-k94.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n384-k52.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n393-k38.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n401-k29.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n411-k19.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n420-k130.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n429-k61.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n439-k37.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n449-k29.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n459-k26.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n469-k138.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n480-k70.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n491-k59.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n502-k39.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n513-k21.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n524-k153.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n536-k96.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n548-k50.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n561-k42.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n573-k30.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n586-k159.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n599-k92.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n613-k62.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n627-k43.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n641-k35.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n655-k131.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n670-k130.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n685-k75.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n701-k44.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n716-k35.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n733-k159.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n749-k98.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n766-k71.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n783-k48.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n801-k40.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n819-k171.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n837-k142.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n856-k95.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n876-k59.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n895-k37.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n916-k207.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n936-k151.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n957-k87.vrp
      x HGS-CVRP-2.0.0/Instances/CVRP/X-n979-k58.vrp
      x HGS-CVRP-2.0.0/LICENSE
      x HGS-CVRP-2.0.0/Program/
      x HGS-CVRP-2.0.0/Program/AlgorithmParameters.cpp
      x HGS-CVRP-2.0.0/Program/AlgorithmParameters.h
      x HGS-CVRP-2.0.0/Program/C_Interface.cpp
      x HGS-CVRP-2.0.0/Program/C_Interface.h
      x HGS-CVRP-2.0.0/Program/CircleSector.h
      x HGS-CVRP-2.0.0/Program/Genetic.cpp
      x HGS-CVRP-2.0.0/Program/Genetic.h
      x HGS-CVRP-2.0.0/Program/Individual.cpp
      x HGS-CVRP-2.0.0/Program/Individual.h
      x HGS-CVRP-2.0.0/Program/InstanceCVRPLIB.cpp
      x HGS-CVRP-2.0.0/Program/InstanceCVRPLIB.h
      x HGS-CVRP-2.0.0/Program/LocalSearch.cpp
      x HGS-CVRP-2.0.0/Program/LocalSearch.h
      x HGS-CVRP-2.0.0/Program/Params.cpp
      x HGS-CVRP-2.0.0/Program/Params.h
      x HGS-CVRP-2.0.0/Program/Population.cpp
      x HGS-CVRP-2.0.0/Program/Population.h
      x HGS-CVRP-2.0.0/Program/Split.cpp
      x HGS-CVRP-2.0.0/Program/Split.h
      x HGS-CVRP-2.0.0/Program/commandline.h
      x HGS-CVRP-2.0.0/Program/main.cpp
      x HGS-CVRP-2.0.0/README.md
      x HGS-CVRP-2.0.0/Test/
      x HGS-CVRP-2.0.0/Test/Test-c/
      x HGS-CVRP-2.0.0/Test/Test-c/CMakeLists.txt
      x HGS-CVRP-2.0.0/Test/Test-c/test.c
      x HGS-CVRP-2.0.0/Test/TestExecutable.cmake
      'cmake' is not recognized as an internal or external command,
      operable program or batch file.
      Build!!!!!! Run!!!!
      Traceback (most recent call last):
        File "C:\Users\agumo\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\agumo\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\agumo\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 103, in <module>
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\normal\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\agumo\AppData\Local\Temp\pip-build-env-dm25zclm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "<string>", line 96, in run
        File "<string>", line 69, in download_build_hgs
        File "<string>", line 28, in _run
        File "C:\Users\agumo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../HGS-CVRP-2.0.0' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hygese
Failed to build hygese
ERROR: Could not build wheels for hygese, which is required to install pyproject.toml-based projects

Have you or some collaborator use hygese on windows recently? 

Thank you for your time.

**Comment by chkwon** [comment]
I was able to use hygese on windows successfully. 

I suggest use 

scoop install gcc make cmake

**Comment by FGE85** [comment]
> I was able to use hygese on windows successfully.
> 
> I suggest use `scoop` to install build tools. https://scoop.sh
> 
> After you install `scoop`, in the powershell prompt, you can run
> 
> ```shell
> PS C:> scoop install gcc make cmake
> ```
> 
> Even you can install python using scoop too:
> 
> ```shell
> PS C:> scoop install python
> ```

This has worked. Thank you !
